"""Physical Security Behavior Ontology for SENTINEL-X.

Defines a controlled vocabulary of observable physical security behaviors.
These are DISTINCT from MITRE ATT&CK techniques. Physical behaviors are
mapped to ATT&CK only when independent cyber domain evidence additionally
supports a technique relationship.
"""

from datetime import datetime, timezone
from enum import Enum
from typing import Optional, List, Dict, Any
from pydantic import BaseModel, Field


class PhysicalBehaviorType(str, Enum):
    """Controlled vocabulary of observable physical security behaviors."""
    LOITERING = "LOITERING"
    TAILGATING = "TAILGATING"
    FORCED_ENTRY = "FORCED_ENTRY"
    RESTRICTED_ZONE_ENTRY = "RESTRICTED_ZONE_ENTRY"
    WEAPON_LIKE_OBJECT = "WEAPON_LIKE_OBJECT"
    CROWD_FORMATION = "CROWD_FORMATION"
    UNUSUAL_MOVEMENT = "UNUSUAL_MOVEMENT"
    OBJECT_ABANDONMENT = "OBJECT_ABANDONMENT"
    ACCESS_CAMERA_MISMATCH = "ACCESS_CAMERA_MISMATCH"
    IMPOSSIBLE_MOVEMENT = "IMPOSSIBLE_MOVEMENT"


class ZoneClassification(str, Enum):
    """Security zone classification hierarchy."""
    PUBLIC = "PUBLIC"
    CONTROLLED = "CONTROLLED"
    RESTRICTED = "RESTRICTED"
    CRITICAL = "CRITICAL"


class BehaviorSeverity(str, Enum):
    """Behavior severity levels (independent of zone)."""
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


# Severity matrix: behavior type + zone -> base severity
BEHAVIOR_ZONE_SEVERITY: Dict[str, Dict[str, str]] = {
    "LOITERING":             {"PUBLIC": "LOW", "CONTROLLED": "MEDIUM", "RESTRICTED": "HIGH",     "CRITICAL": "CRITICAL"},
    "TAILGATING":            {"PUBLIC": "LOW", "CONTROLLED": "MEDIUM", "RESTRICTED": "HIGH",     "CRITICAL": "CRITICAL"},
    "FORCED_ENTRY":          {"PUBLIC": "MEDIUM", "CONTROLLED": "HIGH", "RESTRICTED": "CRITICAL","CRITICAL": "CRITICAL"},
    "RESTRICTED_ZONE_ENTRY": {"PUBLIC": "LOW", "CONTROLLED": "MEDIUM", "RESTRICTED": "CRITICAL","CRITICAL": "CRITICAL"},
    "WEAPON_LIKE_OBJECT":    {"PUBLIC": "HIGH","CONTROLLED": "CRITICAL","RESTRICTED": "CRITICAL","CRITICAL": "CRITICAL"},
    "CROWD_FORMATION":       {"PUBLIC": "LOW", "CONTROLLED": "MEDIUM", "RESTRICTED": "HIGH",     "CRITICAL": "CRITICAL"},
    "UNUSUAL_MOVEMENT":      {"PUBLIC": "LOW", "CONTROLLED": "LOW",    "RESTRICTED": "HIGH",     "CRITICAL": "CRITICAL"},
    "OBJECT_ABANDONMENT":    {"PUBLIC": "MEDIUM","CONTROLLED": "HIGH", "RESTRICTED": "CRITICAL","CRITICAL": "CRITICAL"},
    "ACCESS_CAMERA_MISMATCH":{"PUBLIC": "LOW", "CONTROLLED": "MEDIUM", "RESTRICTED": "HIGH",     "CRITICAL": "CRITICAL"},
    "IMPOSSIBLE_MOVEMENT":   {"PUBLIC": "MEDIUM","CONTROLLED": "HIGH", "RESTRICTED": "HIGH",     "CRITICAL": "CRITICAL"},
}


def get_behavior_severity(behavior: str, zone: str) -> str:
    behavior_map = BEHAVIOR_ZONE_SEVERITY.get(behavior, {})
    return behavior_map.get(zone, "MEDIUM")


class PhysicalBehaviorEvent(BaseModel):
    """Normalized physical security behavior event.

    Generated by the behavior engine from raw camera/sensor observations.
    Distinct from cyber events; mapped to physical security ontology only.
    ATT&CK technique IDs are NOT assigned to this model.
    """
    event_id: str = Field(..., description="Unique behavior event ID")
    behavior_type: PhysicalBehaviorType = Field(..., description="Classified physical behavior")
    camera_id: str = Field(..., description="Source camera sensor ID")
    track_ids: List[str] = Field(default_factory=list, description="Tracked entity IDs involved")
    zone_id: str = Field(..., description="Zone where behavior was detected")
    zone_classification: ZoneClassification = Field(..., description="Zone security classification")
    severity: BehaviorSeverity = Field(..., description="Contextual severity (behavior + zone)")
    behavior_confidence: float = Field(ge=0.0, le=1.0, description="Behavior classification confidence")
    dwell_time_seconds: Optional[float] = Field(None, description="Entity dwell time in zone (LOITERING)")
    entity_count: Optional[int] = Field(None, description="Number of entities involved (CROWD_FORMATION)")
    access_event_id: Optional[str] = Field(None, description="Correlated access control event ID")
    correlated_event_ids: List[str] = Field(default_factory=list, description="Other correlated events")
    movement_trajectory: Optional[str] = Field(None, description="Observed movement sequence description")
    object_class: Optional[str] = Field(None, description="Classified object type (WEAPON_LIKE_OBJECT)")
    physical_note: str = Field(default="", description="Human-readable behavior description")
    situation_id: Optional[str] = Field(None, description="Associated situation ID once correlated")
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

    def to_doc(self) -> Dict[str, Any]:
        doc = self.model_dump()
        doc["timestamp"] = self.timestamp.isoformat()
        return doc
